volumes:
  grafana_data:
  timescaledb_data:

services:
  grafana:
    build:
      context: .
      dockerfile: ./docker/grafana/Dockerfile.grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mesh-bridge
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - timescaledb

  exporter:
    build:
      context: .
      dockerfile: ./docker/exporter/Dockerfile.exporter
    restart: unless-stopped
    depends_on:
      - timescaledb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - mesh-bridge

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    networks:
      - mesh-bridge
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./docker/timescaledb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "meshtastic"

networks:
  mesh-bridge:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
