{
 "title": "PAX Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "query": "SELECT \n  concat(long_name, ' (', node_id, ')') as __text, \n  node_id as __value \nFROM node_details \nORDER BY long_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes map",
   "type": "geomap",
   "description": "Displays nodes on the map and the number of devices around this node",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n    *,\n    EXTRACT(EPOCH FROM now() - updated_at) as age_seconds\nFROM node_details \nWHERE longitude != 0 \nAND longitude IS NOT NULL\nAND node_id IN ($Nodes) "
    },
    {
     "expr": "pax_ble{node_id=~\"$Nodes\"}",
     "legendFormat": "{{node_id}}"
    },
    {
     "expr": "pax_wifi{node_id=~\"$Nodes\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "PAX Uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pax_uptime{node_id=~\"$Nodes\"}",
     "legendFormat": "{{long_name}}"
    }
   ]
  },
  {
   "title": "Distribution of devices",
   "type": "histogram",
   "description": "Distribution of number of devices over time",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Histogram data of Pax counters",
   "type": "heatmap",
   "description": "Histogram for nodes and the number of devices they captured",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 12 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "PAX counters",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pax_ble{node_id=~\"$Nodes\"}",
     "legendFormat": "{{short_name}}-{{node_id}}-Bluetooth"
    },
    {
     "expr": "pax_wifi{node_id=~\"$Nodes\"}",
     "legendFormat": "{{short_name}}-{{node_id}}-Wifi"
    }
   ]
  }
 ]
}