apiVersion: 1
datasources:
  - name: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    jsonData:
      database: meshtastic
      sslmode: "disable"
    user: postgres
    secureJsonData:
      password: postgres
    isDefault: true
    editable: true
